### PR TITLE
provide support for conda

### PR DESCRIPTION
**Pull request by kmnip**
- add requirements file for conda environment
- update readme, usage, and installation
- remove unused option in `tap2.py`
- update parameters for RNA-Bloom

### CODE REVIEW

**Comment by readmanchiu** [comment]
Ka Ming, I have problem creating the conda enviornment:
First, I tried `mamba`. I only have `mamba` installed within a `conda` environment. So either within the `conda` environment, or outside of it using the full path of `mamba`, I couldn't run `mamba activate`. It said I need to run `mamba init` to activate/deactivate, I did not but I still couldn't activate the environment.

Then I tried `conda`. But it gave me this message after I tried `conda install`:
```
(/projects/btl/rchiu/pavfinder) [rchiu@gphost02 pavfinder]$ conda install -f conda_requirements.txt -c conda-forge -c bioconda


WARNING: The --force flag will be removed in a future conda release.
         See 'conda install --help' for details about the --force-reinstall
         and --clobber flags.


Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - conda_requirements.txt

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/r/linux-64
  - https://conda.anaconda.org/r/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/dranew/linux-64
  - https://conda.anaconda.org/dranew/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by readmanchiu** [comment]
oh, I figured out...have to use `--file` instead of `-f`. Maybe it's the version of conda, mine is 4.10.1.

**Comment by kmnip** [comment]
Thanks for catching that. I have update the commands.

**Comment by readmanchiu** [comment]
How do I locate the scripts? I would recommend putting the scripts like `fusion-bloom`, `tap.py`, `tap2.py`, `pavfinder`, `extract_transcript_sequence.py` in the `bin` directory

**Comment by kmnip** [comment]
Right now, I am just setting up the conda environment to run the scripts. How the scripts are run is still exactly the same as how it used to be.

After this is done, we will need to make a release for these changes. Then, we can make a recipe in bioconda.

**Comment by readmanchiu** [comment]
ok, then I would run the script through the git repo locations.
`setup.py` put all the scripts in the `bin` of the local environment. If you install through pip with the github path, all the scripts can be invoked without specifying the path. I think this is desirable to have in the conda environment if there is a way to do it. I guess conda didn't look at `setup.py` when setting up the environment

**Comment by kmnip** [comment]
In that case, I think we need to add some instructions for setting up the `PATH` and `PYTHONPATH`

**Comment by readmanchiu** [comment]
hmmm...how would you run pavfinder after setting up the conda environment then, doesn't seem to work

**Comment by kmnip** [comment]
Added instructions in `INSTALL.md` for setting up `PATH` and `PYTHONPATH`

**Pull request merged**
